### ISSUE TITLE
Fehler beim Laden der CSS und JS im Backend

### ISSUE THREAD

**Issue by arboc** [heimrichhannot/contao-be_explanation-bundle#1]
Das CSS wird über /system/modules/be_explanation/assets/css/be_explanation.css  
und das JS über /system/modules/be_explanation/assets/js/jquery.be_explanation.js  
geladen.

Das sind noch alte Contao 3 Pfade.
Die Pfade müssten eigentlich lauten: 
- /bundles/heimrichhannotcontaobeexplanation/css/be_explanation.css  
- /bundles/heimrichhannotcontaobeexplanation/js/jquery.be_explanation.js

ggf. als min-Versionen.
einfach in der config.php korrigieren.

Danke

**Comment by arboc** [comment]
Nachtrag:

Bei korrigierten Pfaden gibt es dann folgende Fehlermeldung:
```
Uncaught ReferenceError: jQuery is not defined at jquery.be_explanation.js:22
```

Dieser Fehler betrifft auch:
- datatables-additional
- contao-fieldpalette

**Comment by Defcon0** [comment]
Danke fürs Reporten. Ich habe soeben eine neue Version gebaut (https://github.com/heimrichhannot/contao-be_explanation-bundle/tree/2.2.0), die modernen Standards eher entspricht. jQuery ist keine Abhängigkeit mehr und das JavaScript wird durch babel aus einer klassenbasierten ES6-Datei generiert.

Die neue Version ersetzt auch das alte heimrichhannot/contao-be_explanation durch die composer.json, was u.U. parallel installiert war.

**Comment by Defcon0** [comment]
Kannst du es bitte noch mal ausprobieren?

**Comment by arboc** [comment]
passt.  
Danke
